### ISSUE TITLE
switch-relay-on error.

### ISSUE THREAD

**Issue by bvandenbon** [velbus/packetprotocol#1]
As for the example of the "switch-relay-on".
0x0F | 0xF8 | 0x0B | 0x02 | 0x02 | 0x04 | 0xE4 | 0x04

Shouldn't this be 
0x0F | 0xF8 | 0x0B | 0x02 | 0x02 | **0x06** | 0xE4 | 0x04

After all, 2 channels are being changed, and that explains the checksum too.

**Comment by dukeofphilberg** [comment]
Hi there, you're right. I've updated the readme.

Thanks!
